### PR TITLE
Update audio icons

### PR DESCRIPTION
**Pull request by sebromero**
Updates the audio output icons.

### Checklist
- [x] All new and existing tests pass
- [x] I've read the [Contribution Guidelines](https://github.com/arduino/Arduino-Science-Journal-iOS/blob/main/CONTRIBUTING.md)
- [x] I've read [Change Limitations](https://github.com/arduino/Arduino-Science-Journal-iOS/blob/main/CHANGE_LIMITATIONS.md)

### Motivation and Context
The audio icons were not used consistently

### Description
Replaced the mute and volume up icon in the action popup and the sensor card header

### CODE REVIEW

**Review by emiliopavia — APPROVED** [review]
Ok, but is there a reason why you prefer 3 PNGs instead of 1 PDF for icons?

**Comment by sebromero** [comment]
@emiliopavia Only for asset compatibility with Android, but we can do separate PDF exports for iOS if you prefer

**Comment by emiliopavia** [comment]
They're just more manageable (especially if some day in the future Apple will introduce @4x).

**Comment by sebromero** [comment]
Makes sense, let's stick to PDF exports for new assets

**Pull request merged**
