### PR TITLE
Fix action bar issues

### PR DESCRIPTION
**Pull request by emiliopavia**
### Checklist
- [x] All new and existing tests pass
- [x] I've read the [Contribution Guidelines](https://github.com/arduino/Arduino-Science-Journal-iOS/blob/main/CONTRIBUTING.md)
- [x] I've read [Change Limitations](https://github.com/arduino/Arduino-Science-Journal-iOS/blob/main/CHANGE_LIMITATIONS.md)

### Motivation and Context
The current Action Bar implementation suffers some code design flaws. 

The main issue is that the action bar state (normal/modal) is user driven (i.e. tapping on the primary button toggles its state). This means that it doesn't always reflect the real app state, for example:

- when the user taps on Record, but the recording fails to start for some reason, the UI switches to the recording mode no matter what;
- when the recording starts/stops automatically (e.g. because of some triggers setup) the UI doesn't change accordingly.

Another issue it has is related to transitioning and animations between states. The current implementation uses an uncommon technique based on `UIViewControllerTransitionCoordinator`. What it does is presenting a hidden view controller with animation (dismissing it as soon as the presentation ends) and then using its transition coordinator to animate the action bar. While this technique in commonly used when a transition coordinator is actually in place (for example during a real presentation or a navigation in a `UINavigationController`) to create custom animations in sync with system ones, the used approach break things badly if forced this way. For example:

- the view controller hierarchy is broken during a transition, because a useless view controller is presented on top of everything preventing, for example, the presentation of an alert;
- the animation isn't interruptible, so very bad things happen when toggling between states at a fast pace.

### Description
This PR tries to address all these issues in the following ways.

#### Make sure the action bar state changes only if its primary action completes successfully 
In order to achieve this I've made the `action` block in `ActionArea.BarButtonItem` throwable and added the following method to the `ActionAreaBarButtonItemDelegate` protocol:

```Swift
func barButtonItem(_ item: ActionArea.BarButtonItem, didFailActionWithError error: Error)
```

Then in the `execute()` method I've wrapped the `action` in a do-catch block, calling the proper delegate method in either success or failure.

#### Make sure that when the recording state changes, the action bar state changes too
First of all I changed the `ObserveViewControllerDelegate`, adding a parameter to these methods:
```Swift
  func observeViewController(_ observeViewController: ObserveViewController,
                             didStartRecordingFromUserInteraction userInteraction: Bool)

  func observeViewController(_ observeViewController: ObserveViewController,
                             didEndRecordingFromUserInteraction userInteraction: Bool)
```
By doing this we can know if a recording started/stopped because of the user tapping on a button, or automatically by the app. This differentiation is needed because when the action start from the user, the action bar already update its state. If not we need to update the action bar state accordingly. 

Then I added the following method to the `ExperimentCoordinatorViewControllerDelegate` protocol:
```Swift
func experimentViewControllerDidChangeRecordingState()
```

As the `ExperimentCoordinatorViewController` is the delegate of the `ObserveViewController`, it knows when a recording starts/stops programmatically, and can call the previous method to its delegate (the `UserFlowViewController` in our case).

At this point the `UserFlowViewController` that owns the `ActionArea.Controller` can update the action bar state. As it doesn't expose any public method to change its internal state, I've achieved this by calling its `barButtonItemDidExecuteAction()` method.

#### Make use of `UIViewPropertyAnimator` for transitioning
In the current implementation there are several helper methods that drive UI animations and transitions, and that took the `UIViewControllerTransitionCoordinator` as a parameter. As we want to maintain the use of transition coordinators for animations when it makes sense (for example when navigating from the main screen to the experiment and vice versa), and also we don't want to duplicate code, I've added an additional parameter to these methods that passes also a `UIViewPropertyAnimator`. The last method that actually performs the animation can choose what "animator" to use:
```Swift
private func transition(
      before: () -> Void = {},
      during: @escaping () -> Void = {},
      after: @escaping () -> Void = {},
      with coordinator: UIViewControllerTransitionCoordinator?,
      or animator: UIViewPropertyAnimator?
    )
```
The `initiateLocalTransition()` method that made the hack of presenting a hidden view controller has been replaced by the new `animate()` function that instead returns the `UIViewPropertyAnimator`.

### CODE REVIEW

**Comment by sebromero** [comment]
@emiliopavia 
Class ✨  The only thing I'd rethink is the naming of the transition parameters.
```
func transition(
     _ type: TransitionType,
     with coordinator: UIViewControllerTransitionCoordinator?,
     or animator: UIViewPropertyAnimator?
)
```
looks a little odd to me with `transition(t, with: nil, or: animator)`
I think I'd personally go with `coordinator` and `animator` as parameter labels. What do you think?

**Comment by emiliopavia** [comment]
> looks a little odd to me with `transition(t, with: nil, or: animator)`
> I think I'd personally go with `coordinator` and `animator` as parameter labels. What do you think?

I absolutely agree with you... I got stuck with that naming for half an hour, changing it several times but I couldn't find a good one 🙄
Maybe it's better to keep it simple as you suggest.

**Comment by emiliopavia** [comment]
@sebromero I've renamed methods.

**Review by sebromero — APPROVED** [review]
LGTM

**Pull request merged**
